### ISSUE TITLE
Need to make RTD public

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-tabu#26]
Clicking on the RTD link:
![image](https://user-images.githubusercontent.com/34041130/49184130-6ccb6f80-f313-11e8-9390-c4d61d62fd4a.png)

Asks clicker to log in to RTDs. This is because it has not been set to public:

![image](https://user-images.githubusercontent.com/34041130/49184076-4574a280-f313-11e8-9de4-89493287dd76.png)

**Comment by arcondello** [comment]
Done
