### ISSUE TITLE
Default value of 1 for `scale_factor` means bad results bqms with non-integer biases

### ISSUE THREAD

**Issue by wbernoudy** [dwavesystems/dwave-tabu#29]
Though the parameter `scale_factor` is documented, the default behavior means casting all biases to `int` (not just rounding, but truncating the fractional part) which can be pathological for anything but very low precision problems.

A quick example (note I don't fully understand this as I would think it should produce random samples):
```python
In [21]: tabu_sampler.sample_ising({0: 0.4}, {}, num_reads=100).record.energy.mean()                                                                                                     
Out[21]: 0.3999999999999999
```

`scale_factor` should probably be set internally in the `sample` method, determined by the bqm range of biases. I can't think of any use-case that requires exposing it (though please mention it if there is one!)

**Comment by arcondello** [comment]
In this case it's uneven because it is transformed into a QUBO first, so the scaled problem is actually
```
Q = {(0, 0): 0.8}
offset = -0.4
```
