### ISSUE TITLE
Blocker to https://github.com/dwavesystems/docs/issues/57 ?

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-tabu#32]
Before I fix https://github.com/dwavesystems/docs/issues/57, with links to RTD, I think the RTD for dwave-tabu should be **dwave-tabu** under https://docs.ocean.dwavesys.com/projects, not **d-wave-systems-dwave-tabu** as it is currently:

If there's some good reason for this inconsistent format, let me know. Thanks!

**Comment by arcondello** [comment]
Fixed. https://docs.ocean.dwavesys.com/projects/tabu. Also updated the link on the front page

**Comment by randomir** [comment]
both dwave-tabu or tabu are fine. the longer variant was the default if i remember correctly...
