### ISSUE TITLE
Doctests failing in Sphinx 2.0

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-tabu#35]
See https://circleci.com/gh/dwavesystems/dwave-tabu/1129.

Doctests do work for Sphinx < 2.0.

**Comment by JoelPasvolsky** [comment]
@randomir please check your requirements files, you might need to rebuild for changed dependencies. There's a mismatch between "RuntimeError: tenure must be in the range [1, num_vars - 1]"  and latest version where "throw Exception("tenure must be in the range [0, num_vars - 1]");"

I can recreate the error (before rebuilding locally):

In [1]: from tabu import TabuSampler
In [2]: import dimod
In [3]: sampler = TabuSampler()
In [4]: Q = {(0, 0): -1, (1, 1): -1, (0, 1): 2}
In [5]: bqm = dimod.BinaryQuadraticModel.from_qubo(Q, offset=0.0)
In [12]: samples = sampler.sample(bqm)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-19bd5cd81048> in <module>()
----> 1 samples = sampler.sample(bqm)

~\!git_DocsOS\env3\ADTT\dwave-tabu\tabu\sampler.py in sample(self, bqm, init_solution, tenure, scale_factor, timeout, num_reads)
    128             if init_sample is None:
    129                 init_sample = self._bqm_sample_to_tabu_sample(self._random_sample(bqm.binary), bqm.binary)
--> 130             r = TabuSearch(qubo, init_sample, tenure, scale_factor, timeout)
    131             sample = self._tabu_sample_to_bqm_sample(list(r.bestSolution()), bqm.binary)
    132             energy = bqm.binary.energy(sample)

~\!git_DocsOS\env3\ADTT\dwave-tabu\tabu\tabu_search.py in __init__(self, Q, initSol, tenure, scaleFactor, timeout)
    657         solution = handler.bestSolution()
    658         """
--> 659         this = _tabu_search.new_TabuSearch(Q, initSol, tenure, scaleFactor, timeout)
    660         try:
    661             self.this.append(this)

RuntimeError: tenure must be in the range [1, num_vars - 1]

Once I rebuild:

In [1]: from tabu import TabuSampler
In [2]: import dimod
In [3]: sampler = TabuSampler()
In [4]: Q = {(0, 0): -1, (1, 1): -1, (0, 1): 2}
In [5]: bqm = dimod.BinaryQuadraticModel.from_qubo(Q, offset=0.0)
In [6]: samples = sampler.sample(bqm)
In [7]:

**Comment by JoelPasvolsky** [comment]
After building the C files locally:

Doctest summary
===============
   21 tests
    0 failures in tests
    0 failures in setup code
    0 failures in cleanup code
build succeeded, 3 warnings.

**Comment by randomir** [comment]
Doctests are failing on a fresh install of dependencies, because Sphinx 2.0 is then used.

Can you check doctests work for you with Sphinx==2.0.0?

**Comment by JoelPasvolsky** [comment]
Well, that spoils things. 

Doctest summary
===============
   21 tests
    8 failures in tests
    0 failures in setup code
    0 failures in cleanup code
build finished with problems, 3 warnings.

**Comment by JoelPasvolsky** [comment]
sphinx has versions "...1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 2.0.0b1, 2.0.0b2, 2.0.0)" and doctest works for versions <=1.8.5 but fails test for versions >= 2.0x.
Running doctest directly on dwave-tabu succeeds with no failed tests. It looks to me like this might be a sphinx-build problem.
@randomir, would setting a requirement "sphinx<=1.85" be an acceptable workaround?

**Comment by randomir** [comment]
@JoelPasvolsky, that's how I did it for now (in PR #34), but we should look into the root cause for this.

**Comment by JoelPasvolsky** [comment]
👍

**Comment by JoelPasvolsky** [comment]
I think PR #36 should fix this. I'm running sphinx-build doctest with sphinx version 2.0.0 and all tests pass:

```
Doctest summary
===============
   14 tests
    0 failures in tests
    0 failures in setup code
    0 failures in cleanup code
build succeeded.
```
