### ISSUE TITLE
Tabu sampler is not compatible with AdjArrayBQM

### ISSUE THREAD

**Issue by tadakado** [dwavesystems/dwave-tabu#59]
Hi Team,

The new BQM generators, such as AdjArrayBQM, are really cool!
But, Tabu sampler can't handle the new objects.
Are you planing to fix it?

Best,

**Comment by arcondello** [comment]
Hi @tadakado , absolutely! Should be in the next few weeks.

**Comment by arcondello** [comment]
See also https://github.com/dwavesystems/dwave-tabu/pull/56

**Comment by tadakado** [comment]
Looking for the next release!!!

**Comment by randomir** [comment]
Reopening until #56 is merged.
