### ISSUE TITLE
fails to give global minima

### ISSUE THREAD

**Issue by davidbhatt** [dwavesystems/dwave-tabu#96]
I am trying to solve a qubo problem using dwave tabu. I am using the python interface with the following commands.
`from tabu import TabuSampler
response = TabuSampler().sample_qubo(Q)
print(response.first.energy)`
every time I run, I am getting different values of energy and solution. I am getting energy close to the global minimum, but not global minima. 
whereas qbsolv command gives global minima every time. what is the problem or am I missing something?

**Comment by randomir** [comment]
dwave-tabu and qbsolv are different solvers. They both use the tabu algorithm, but tuned differently. Also, qbsolv is a hybrid solver in a sense that it solves subproblems using a subsolver like QPU (or tabu again in "classical" mode).

Ultimately, each of them will perform better on some problems and worse on other. Unless you're running them on a simple problem, minimizing which is easy. In that case you might have found a bug. Can you share more details about your problem and/or the problem itself? Thanks.

**Comment by randomir** [comment]
Closing as stale.
